require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - Rakefile
    - bin/**/*
    - gemfiles/**/*
    - spec/dummy/db/schema.rb
    - vendor/bundle/**/*
  NewCops: enable

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndAlignment:
  AutoCorrect: true
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  AllowedPatterns:
    - \#\s

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/MissingSuper:
  Enabled: false

Lint/SymbolConversion:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - lib/tasks/**/*
    - spec/**/*

Metrics/ClassLength:
  CountAsOne: ["array", "hash", "heredoc"]

Metrics/MethodLength:
  CountAsOne: ["array", "hash", "heredoc"]

Naming/MethodParameterName:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ExampleLength:
  CountAsOne: ["array", "hash", "heredoc"]
  Max: 10

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Security/Eval:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EndlessMethod:
  Enabled: false

Style/TrailingBodyOnMethodDefinition:
  Enabled: false

Style/TrailingMethodEndStatement:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/RedundantCapitalW:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Send:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
