name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.2"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install Appraisal dependencies
        run: bundle exec appraisal install

      - name: Appraise Rails 6.1
        run: bundle exec appraisal rails-6.1 rspec

      - name: Appraise Rails 7.0
        run: bundle exec appraisal rails-7.0 rspec

      - name: Appraise Rails 7.1
        run: bundle exec appraisal rails-7.1 rspec

      - name: Appraise Rails Edge
        run: bundle exec appraisal rails-edge rspec

      - name: Lint with Rubocop
        run: bundle exec rubocop
